### ISSUE TITLE
noticed some break changes in the pre-release of the python-transmisionrpc package

### ISSUE THREAD

**Issue by wuliaotc** [blind-oracle/transmission-trackers#15]
## transmisionrpc packge（ver:4.0.0a5）changes
1. packge name form transmissionrpc to transmission_rpc
2. Some filed are replaced with property
   - toorrent.isPrivate to is_private
   - trackers['announce'] to announce

**I didn't check all the break changes in the rpc package in the pre-release,** these adjustments just make him run on my machine.

Might want to check for other break changes once version 4.0 of the rpc package is released.

https://github.com/blind-oracle/transmission-trackers/commit/a4ad0acb8a2cd770a23ead949bdea42fd8be2ce4
## bug fix
1. By the way, I fixed two possible problems https://github.com/blind-oracle/transmission-trackers/commit/e5c6e3f347168744fe29c701c655613c20b216ba

**Comment by ahmubashshir** [comment]
This was fixed in #16

**Comment by wuliaotc** [comment]
> This was fixed in #16

Thanks for your great work. Just to confirm, are these two fields the only changes that need to be compatible?
